POST http:localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}

###

GET http:localhost:3333/courses

###

GET http:localhost:3333/courses/ac3d0a90-809a-4b80-8043-e7b227afc673