POST http:localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Bun"
}

###

GET http:localhost:3333/courses

###

GET http:localhost:3333/courses?search=an

###

GET http:localhost:3333/courses?orderBy=title

###

GET http:localhost:3333/courses?orderBy=title&page=2

###

GET http:localhost:3333/courses/ced9d9be-8c02-46bd-a0e5-ef893b163344

###

DELETE http:localhost:3333/courses/f9e51080-bb34-4767-a96a-5912795e62fe